'use client';
import {Check,Copy,Loader2,AlertCircle,ChevronDown} from 'lucide-react';
import {useState} from 'react';
export function Button({children,variant='primary',loading=false,...p}:{children:React.ReactNode;variant?:'primary'|'secondary'|'ghost'|'danger';loading?:boolean}&React.ButtonHTMLAttributes<HTMLButtonElement>){const styles={primary:'bg-[var(--accent)] text-white border-[var(--accent)] hover:opacity-90',secondary:'bg-[var(--surface)] border-line hover:bg-[var(--surface2)]',ghost:'border-transparent hover:bg-[var(--surface2)]',danger:'bg-[var(--danger)] text-white border-[var(--danger)] hover:opacity-90'};return <button {...p} disabled={loading||p.disabled} className={`focus-ring inline-flex min-h-10 items-center justify-center gap-2 rounded-lg border px-4 py-2 text-sm font-semibold transition disabled:cursor-not-allowed disabled:opacity-50 ${styles[variant]} ${p.className||''}`}>{loading?<Loader2 className="animate-spin" size={16}/>:null}{children}</button>}
export function Field({label,children,hint,required}:{label:string;children:React.ReactNode;hint?:string;required?:boolean}){return <div className="space-y-2"><label className="block text-sm font-semibold">{label}{required?<span aria-hidden="true"> *</span>:null}</label>{children}{hint?<p className="text-xs muted">{hint}</p>:null}</div>}
export function Input(p:React.InputHTMLAttributes<HTMLInputElement>){return <input {...p} className={`focus-ring min-h-11 w-full rounded-lg border border-line bg-[var(--surface)] px-3.5 text-sm outline-none focus:border-[var(--accent)] ${p.className||''}`}/>}
export function Textarea(p:React.TextareaHTMLAttributes<HTMLTextAreaElement>){return <textarea {...p} className={`focus-ring min-h-32 w-full rounded-lg border border-line bg-[var(--surface)] px-3.5 py-3 text-sm outline-none focus:border-[var(--accent)] ${p.className||''}`}/>}
export function Select(p:React.SelectHTMLAttributes<HTMLSelectElement>){return <div className="relative"><select {...p} className={`focus-ring min-h-11 w-full appearance-none rounded-lg border border-line bg-[var(--surface)] px-3.5 pr-9 text-sm outline-none focus:border-[var(--accent)] ${p.className||''}`}/><ChevronDown aria-hidden className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 muted" size={16}/></div>}
export function Score({value,label}:{value:number;label:string}){return <div><div className="mb-1.5 flex justify-between text-xs"><span className="muted">{label}</span><strong>{value}</strong></div><div className="h-2 overflow-hidden rounded-full bg-[var(--surface2)]"><div className="h-full rounded-full bg-[var(--accent)]" style={{width:`${value}%`}}/></div></div>}
export function CopyButton({text}:{text:string}){const [done,setDone]=useState(false);return <Button variant="ghost" onClick={async()=>{try{await navigator.clipboard.writeText(text);setDone(true);window.setTimeout(()=>setDone(false),1400)}catch{}}} aria-label="Copy text to clipboard">{done?<Check size={15}/>:<Copy size={15}/>} {done?'Copied':'Copy'}</Button>}
export function Notice({children,kind='error'}:{children:React.ReactNode;kind?:'error'|'info'|'success'}){return <div role={kind==='error'?'alert':'status'} className="flex gap-3 rounded-lg border border-line bg-[var(--surface2)] p-4 text-sm"><AlertCircle size={18} className="shrink-0"/><div>{children}</div></div>}
